import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FFFBF5]">
      <nav className="max-w-3xl mx-auto px-6 py-6">
        <Link
          href="/"
          className="text-sm text-stone-500 hover:text-orange-500 transition-colors"
        >
          &larr; Back to home
        </Link>
      </nav>

      <main className="max-w-3xl mx-auto px-6 pb-20">
        <h1 className="text-3xl font-bold text-stone-900 mb-8">
          Terms of Service
        </h1>

        <div className="prose prose-stone prose-sm max-w-none space-y-6 text-stone-600">
          <p>
            <strong>Last updated:</strong> February 2026
          </p>

          <h2 className="text-lg font-semibold text-stone-800">The service</h2>
          <p>
            What&apos;s For Dinner provides AI-generated personalized meal plans
            and grocery lists delivered via email. Plans are generated using
            artificial intelligence and are intended as suggestions — not medical
            or nutritional advice.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">Free plan</h2>
          <p>
            You can generate one free 1-day meal plan without creating an
            account. No credit card is required for the free plan.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">
            Subscriptions
          </h2>
          <p>
            Paid subscriptions are billed monthly ($4.99/mo) or yearly
            ($29.99/yr) through Lemon Squeezy. You can cancel anytime from your
            dashboard or the Lemon Squeezy customer portal. Access continues
            through the end of the billing period.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">
            Regenerations
          </h2>
          <p>
            Subscribers can regenerate their weekly meal plan up to 2 times per
            week. Unused regenerations do not carry over.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">Disclaimer</h2>
          <p>
            Meal plans are generated by AI and may not be suitable for all
            dietary needs. Always consult a healthcare professional for specific
            medical or nutritional advice. We are not liable for any adverse
            effects from following the generated meal plans.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">
            Account termination
          </h2>
          <p>
            We reserve the right to suspend or terminate accounts that abuse the
            service, including but not limited to: circumventing free plan
            limits, automated scraping, or using the service for commercial
            redistribution.
          </p>

          <h2 className="text-lg font-semibold text-stone-800">Contact</h2>
          <p>
            Questions? Email us at{" "}
            <a
              href="mailto:hello@whatsfordinner.fit"
              className="text-orange-500 hover:text-orange-600"
            >
              hello@whatsfordinner.fit
            </a>
            .
          </p>
        </div>
      </main>
    </div>
  );
}
